#ifndef GUARD_GENERATED_ANIM_CODE_FooBar_H
#define GUARD_GENERATED_ANIM_CODE_FooBar_H

// Ensure INCBIN_U16 is available
#ifndef INCBIN_U16
#include "gba/defines.h"
#endif

/*
 * This file is auto-generated by Porytiles.
 * DO NOT EDIT THIS FILE MANUALLY (unless you know what you are doing).
 */

// ============================================
// Frame Data (INCBIN statements)
// ============================================

const u16 gTilesetAnims_PorytilesManaged_FooBar_Flower_FrameCenter[] = INCBIN_U16("data/tilesets/primary/foo_bar/porytiles_bin/anim/flower/center.4bpp");
const u16 gTilesetAnims_PorytilesManaged_FooBar_Flower_FrameRight[] = INCBIN_U16("data/tilesets/primary/foo_bar/porytiles_bin/anim/flower/right.4bpp");
const u16 gTilesetAnims_PorytilesManaged_FooBar_Flower_FrameLeft[] = INCBIN_U16("data/tilesets/primary/foo_bar/porytiles_bin/anim/flower/left.4bpp");

// ============================================
// Frame Pointer Arrays
// ============================================

const u16 *const gTilesetAnims_PorytilesManaged_FooBar_Flower[] = {
    gTilesetAnims_PorytilesManaged_FooBar_Flower_FrameCenter,
    gTilesetAnims_PorytilesManaged_FooBar_Flower_FrameRight,
    gTilesetAnims_PorytilesManaged_FooBar_Flower_FrameCenter,
    gTilesetAnims_PorytilesManaged_FooBar_Flower_FrameLeft
};

// ============================================
// Queue Functions
// ============================================

static void QueueAnimTiles_PorytilesManaged_FooBar_Flower(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_FooBar_Flower);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_FooBar_Flower[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(1)), 4 * TILE_SIZE_4BPP);
}

// ============================================
// Driver Function
// ============================================

static void TilesetAnim_PorytilesManaged_FooBar(u16 timer)
{
    if (timer % 16 == 0)
    {
        QueueAnimTiles_PorytilesManaged_FooBar_Flower(timer / 16);
    }
}

// ============================================
// Init Function
// ============================================

void InitTilesetAnim_PorytilesManaged_FooBar(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_PorytilesManaged_FooBar;
}

#endif // GUARD_GENERATED_ANIM_CODE_FooBar_H
